# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import operator_pb2 as operator__pb2


class GameStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetResult = channel.unary_unary(
        '/Game/GetResult',
        request_serializer=operator__pb2.Req.SerializeToString,
        response_deserializer=operator__pb2.Resp.FromString,
        )


class GameServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetResult(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GameServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetResult': grpc.unary_unary_rpc_method_handler(
          servicer.GetResult,
          request_deserializer=operator__pb2.Req.FromString,
          response_serializer=operator__pb2.Resp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Game', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
